//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickPay.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClickPay.Shared.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a I accept the terms.
        /// </summary>
        public static string AcceptDisclaimer {
            get {
                return ResourceManager.GetString("AcceptDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Address:.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Amount:.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Authentication cancelled..
        /// </summary>
        public static string BiometricAuthCanceled {
            get {
                return ResourceManager.GetString("BiometricAuthCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Biometric authentication failed..
        /// </summary>
        public static string BiometricAuthFailed {
            get {
                return ResourceManager.GetString("BiometricAuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Biometric authentication is required to continue..
        /// </summary>
        public static string BiometricOverlayPrompt {
            get {
                return ResourceManager.GetString("BiometricOverlayPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Protection enabled.
        /// </summary>
        public static string BiometricOverlayTitle {
            get {
                return ResourceManager.GetString("BiometricOverlayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Try again.
        /// </summary>
        public static string BiometricRetryButton {
            get {
                return ResourceManager.GetString("BiometricRetryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm your identity to continue..
        /// </summary>
        public static string BiometricUnlockPrompt {
            get {
                return ResourceManager.GetString("BiometricUnlockPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unlock ClickPay.
        /// </summary>
        public static string BiometricUnlockTitle {
            get {
                return ResourceManager.GetString("BiometricUnlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a BTC transaction broadcast failed: {0} - {1}.
        /// </summary>
        public static string BitcoinTransactionBroadcastFailed {
            get {
                return ResourceManager.GetString("BitcoinTransactionBroadcastFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The blockchain node returned an error..
        /// </summary>
        public static string BlockchainNodeError {
            get {
                return ResourceManager.GetString("BlockchainNodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Click me.
        /// </summary>
        public static string ClickMe {
            get {
                return ResourceManager.GetString("ClickMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Saving….
        /// </summary>
        public static string CommonSavingInProgress {
            get {
                return ResourceManager.GetString("CommonSavingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm and create wallet.
        /// </summary>
        public static string ConfirmCreateWalletButton {
            get {
                return ResourceManager.GetString("ConfirmCreateWalletButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm and restore.
        /// </summary>
        public static string ConfirmRestoreWalletButton {
            get {
                return ResourceManager.GetString("ConfirmRestoreWalletButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confirm Swap.
        /// </summary>
        public static string ConfirmSwap {
            get {
                return ResourceManager.GetString("ConfirmSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Conversion successful!.
        /// </summary>
        public static string ConversionSuccess {
            get {
                return ResourceManager.GetString("ConversionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Convert.
        /// </summary>
        public static string Converti {
            get {
                return ResourceManager.GetString("Converti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select and copy the text below:.
        /// </summary>
        public static string CopyModalDescription {
            get {
                return ResourceManager.GetString("CopyModalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Copy text.
        /// </summary>
        public static string CopyModalTitle {
            get {
                return ResourceManager.GetString("CopyModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Copy payment request.
        /// </summary>
        public static string CopyPaymentRequest {
            get {
                return ResourceManager.GetString("CopyPaymentRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Counter.
        /// </summary>
        public static string CounterHeading {
            get {
                return ResourceManager.GetString("CounterHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Counter.
        /// </summary>
        public static string CounterTitle {
            get {
                return ResourceManager.GetString("CounterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create new wallet.
        /// </summary>
        public static string CreateWalletButton {
            get {
                return ResourceManager.GetString("CreateWalletButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This is your 24-word passphrase. Write it down and keep it safe..
        /// </summary>
        public static string CreateWalletInstructions {
            get {
                return ResourceManager.GetString("CreateWalletInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New Wallet.
        /// </summary>
        public static string CreateWalletTitle {
            get {
                return ResourceManager.GetString("CreateWalletTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Current count:.
        /// </summary>
        public static string CurrentCount {
            get {
                return ResourceManager.GetString("CurrentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nobody, including ClickPay, can access your wallets or keys. Your data is protected and not shared or synced to the cloud, unless the encryption is robust zero-knowledge and quantum-proof. Keep your passphrase safe: it is the only way to access your funds..
        /// </summary>
        public static string DisclaimerText1 {
            get {
                return ResourceManager.GetString("DisclaimerText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ClickPay Wallet Privacy.
        /// </summary>
        public static string DisclaimerTitle {
            get {
                return ResourceManager.GetString("DisclaimerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Destination address is required..
        /// </summary>
        public static string ErrorDestinationRequired {
            get {
                return ResourceManager.GetString("ErrorDestinationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Amount must be positive..
        /// </summary>
        public static string ErrorInvalidAmount {
            get {
                return ResourceManager.GetString("ErrorInvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reload.
        /// </summary>
        public static string ErrorReloadLink {
            get {
                return ResourceManager.GetString("ErrorReloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An unexpected error has occurred..
        /// </summary>
        public static string ErrorUnhandledMessage {
            get {
                return ResourceManager.GetString("ErrorUnhandledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unsupported asset..
        /// </summary>
        public static string ErrorUnsupportedAsset {
            get {
                return ResourceManager.GetString("ErrorUnsupportedAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ethereum RPC error: {0}.
        /// </summary>
        public static string EthereumRpcError {
            get {
                return ResourceManager.GetString("EthereumRpcError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Amount to exchange.
        /// </summary>
        public static string ExchangeAmount {
            get {
                return ResourceManager.GetString("ExchangeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Available:.
        /// </summary>
        public static string ExchangeBalanceInfoLabel {
            get {
                return ResourceManager.GetString("ExchangeBalanceInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Exchange.
        /// </summary>
        public static string ExchangeButton {
            get {
                return ResourceManager.GetString("ExchangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Exchange one asset for another at the best available rate. Only visible resources are available for trading..
        /// </summary>
        public static string ExchangeDescription {
            get {
                return ResourceManager.GetString("ExchangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The amount exceeds your available balance..
        /// </summary>
        public static string ExchangeErrorAmountExceedsBalance {
            get {
                return ResourceManager.GetString("ExchangeErrorAmountExceedsBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter a valid amount to exchange..
        /// </summary>
        public static string ExchangeErrorAmountRequired {
            get {
                return ResourceManager.GetString("ExchangeErrorAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select two different assets to trade..
        /// </summary>
        public static string ExchangeErrorSelectDifferentAssets {
            get {
                return ResourceManager.GetString("ExchangeErrorSelectDifferentAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please note: the transaction fee is higher than usual..
        /// </summary>
        public static string ExchangeFeeHighWarning {
            get {
                return ResourceManager.GetString("ExchangeFeeHighWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Estimated transaction fee.
        /// </summary>
        public static string ExchangeFeePercentLabel {
            get {
                return ResourceManager.GetString("ExchangeFeePercentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a As a resource.
        /// </summary>
        public static string ExchangeFromAsset {
            get {
                return ResourceManager.GetString("ExchangeFromAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Exchange.
        /// </summary>
        public static string ExchangeMenuTitle {
            get {
                return ResourceManager.GetString("ExchangeMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No commission applied.
        /// </summary>
        public static string ExchangeNoFee {
            get {
                return ResourceManager.GetString("ExchangeNoFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Choose the percentage of your balance.
        /// </summary>
        public static string ExchangePercentLabel {
            get {
                return ResourceManager.GetString("ExchangePercentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a of your balance.
        /// </summary>
        public static string ExchangePercentOfBalanceLabel {
            get {
                return ResourceManager.GetString("ExchangePercentOfBalanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Direct rate.
        /// </summary>
        public static string ExchangeRateDirectLabel {
            get {
                return ResourceManager.GetString("ExchangeRateDirectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error calculating exchange rate: {0}.
        /// </summary>
        public static string ExchangeRateError {
            get {
                return ResourceManager.GetString("ExchangeRateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reverse rate.
        /// </summary>
        public static string ExchangeRateInverseLabel {
            get {
                return ResourceManager.GetString("ExchangeRateInverseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to contact the exchange rate provider. Check your connection and try again..
        /// </summary>
        public static string ExchangeRateNetworkError {
            get {
                return ResourceManager.GetString("ExchangeRateNetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Exchange rate not available for this pair..
        /// </summary>
        public static string ExchangeRateNotAvailable {
            get {
                return ResourceManager.GetString("ExchangeRateNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The exchange rate request has expired. Please try again later..
        /// </summary>
        public static string ExchangeRateTimeoutError {
            get {
                return ResourceManager.GetString("ExchangeRateTimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An unexpected error occurred while retrieving exchange rates..
        /// </summary>
        public static string ExchangeRateUnknownError {
            get {
                return ResourceManager.GetString("ExchangeRateUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Upgrade Rates….
        /// </summary>
        public static string ExchangeRefreshingRates {
            get {
                return ResourceManager.GetString("ExchangeRefreshingRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Exchange completed successfully!.
        /// </summary>
        public static string ExchangeSuccessMessage {
            get {
                return ResourceManager.GetString("ExchangeSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rate applied.
        /// </summary>
        public static string ExchangeSummaryFeeApplied {
            get {
                return ResourceManager.GetString("ExchangeSummaryFeeApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Net received.
        /// </summary>
        public static string ExchangeSummaryNetReceived {
            get {
                return ResourceManager.GetString("ExchangeSummaryNetReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Total charged.
        /// </summary>
        public static string ExchangeSummaryTotalDebited {
            get {
                return ResourceManager.GetString("ExchangeSummaryTotalDebited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A resource.
        /// </summary>
        public static string ExchangeToAsset {
            get {
                return ResourceManager.GetString("ExchangeToAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Australian Dollar.
        /// </summary>
        public static string FiatCurrency_AUD {
            get {
                return ResourceManager.GetString("FiatCurrency_AUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Canadian Dollar.
        /// </summary>
        public static string FiatCurrency_CAD {
            get {
                return ResourceManager.GetString("FiatCurrency_CAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Swiss Franc.
        /// </summary>
        public static string FiatCurrency_CHF {
            get {
                return ResourceManager.GetString("FiatCurrency_CHF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chinese Yuan.
        /// </summary>
        public static string FiatCurrency_CNY {
            get {
                return ResourceManager.GetString("FiatCurrency_CNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Euro.
        /// </summary>
        public static string FiatCurrency_EUR {
            get {
                return ResourceManager.GetString("FiatCurrency_EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a British Pound.
        /// </summary>
        public static string FiatCurrency_GBP {
            get {
                return ResourceManager.GetString("FiatCurrency_GBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hong Kong Dollar.
        /// </summary>
        public static string FiatCurrency_HKD {
            get {
                return ResourceManager.GetString("FiatCurrency_HKD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indian Rupee.
        /// </summary>
        public static string FiatCurrency_INR {
            get {
                return ResourceManager.GetString("FiatCurrency_INR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Japanese Yen.
        /// </summary>
        public static string FiatCurrency_JPY {
            get {
                return ResourceManager.GetString("FiatCurrency_JPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Singapore Dollar.
        /// </summary>
        public static string FiatCurrency_SGD {
            get {
                return ResourceManager.GetString("FiatCurrency_SGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a US Dollar.
        /// </summary>
        public static string FiatCurrency_USD {
            get {
                return ResourceManager.GetString("FiatCurrency_USD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Choose the currency you want to use when showing your asset values..
        /// </summary>
        public static string FiatPreferenceDescription {
            get {
                return ResourceManager.GetString("FiatPreferenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reference currency.
        /// </summary>
        public static string FiatPreferenceTitle {
            get {
                return ResourceManager.GetString("FiatPreferenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a From asset.
        /// </summary>
        public static string FromAsset {
            get {
                return ResourceManager.GetString("FromAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Generate Request.
        /// </summary>
        public static string GenerateRequest {
            get {
                return ResourceManager.GetString("GenerateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gold.
        /// </summary>
        public static string GoldWalletMenuLabel {
            get {
                return ResourceManager.GetString("GoldWalletMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Convert.
        /// </summary>
        public static string NavMenu_Convert {
            get {
                return ResourceManager.GetString("NavMenu_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disclaimer.
        /// </summary>
        public static string NavMenu_Disclaimer {
            get {
                return ResourceManager.GetString("NavMenu_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pay.
        /// </summary>
        public static string NavMenu_Pay {
            get {
                return ResourceManager.GetString("NavMenu_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Resetting wallet….
        /// </summary>
        public static string NavMenu_ResettingWallet {
            get {
                return ResourceManager.GetString("NavMenu_ResettingWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset wallet (debug).
        /// </summary>
        public static string NavMenu_ResetWalletDebug {
            get {
                return ResourceManager.GetString("NavMenu_ResetWalletDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Setup.
        /// </summary>
        public static string NavMenu_Setup {
            get {
                return ResourceManager.GetString("NavMenu_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No balance available to select percentage..
        /// </summary>
        public static string NoBalanceForPercentage {
            get {
                return ResourceManager.GetString("NoBalanceForPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No transactions available..
        /// </summary>
        public static string NoTransactionsMessage {
            get {
                return ResourceManager.GetString("NoTransactionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The passphrase is the only way to recover your wallet. Do not lose it!.
        /// </summary>
        public static string PassphraseWarning {
            get {
                return ResourceManager.GetString("PassphraseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ≈ {0} EUR.
        /// </summary>
        public static string Pay_EuroEquivalent {
            get {
                return ResourceManager.GetString("Pay_EuroEquivalent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scan cancelled..
        /// </summary>
        public static string Pay_ScanCancelled {
            get {
                return ResourceManager.GetString("Pay_ScanCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scanning in progress....
        /// </summary>
        public static string Pay_ScanningInProgress {
            get {
                return ResourceManager.GetString("Pay_ScanningInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tap to retry..
        /// </summary>
        public static string Pay_TapToRetry {
            get {
                return ResourceManager.GetString("Pay_TapToRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pay.
        /// </summary>
        public static string PayTitle {
            get {
                return ResourceManager.GetString("PayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a QR Code.
        /// </summary>
        public static string QRCode {
            get {
                return ResourceManager.GetString("QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a QR shop.
        /// </summary>
        public static string QRMerchant {
            get {
                return ResourceManager.GetString("QRMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a QR Personale.
        /// </summary>
        public static string QRPersonale {
            get {
                return ResourceManager.GetString("QRPersonale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a QR scanning failed..
        /// </summary>
        public static string QrScan_Error_Generic {
            get {
                return ResourceManager.GetString("QrScan_Error_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to initialize the QR scanner..
        /// </summary>
        public static string QrScan_Error_InitFailed {
            get {
                return ResourceManager.GetString("QrScan_Error_InitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid address in QR..
        /// </summary>
        public static string QrScan_Error_InvalidAddress {
            get {
                return ResourceManager.GetString("QrScan_Error_InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid amount in QR..
        /// </summary>
        public static string QrScan_Error_InvalidAmount {
            get {
                return ResourceManager.GetString("QrScan_Error_InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid QR format..
        /// </summary>
        public static string QrScan_Error_InvalidFormat {
            get {
                return ResourceManager.GetString("QrScan_Error_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The browser does not support native QR detection..
        /// </summary>
        public static string QrScan_Error_NoBarcodeApi {
            get {
                return ResourceManager.GetString("QrScan_Error_NoBarcodeApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This browser cannot access the camera..
        /// </summary>
        public static string QrScan_Error_NoCamera {
            get {
                return ResourceManager.GetString("QrScan_Error_NoCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The QR code does not contain any data..
        /// </summary>
        public static string QrScan_Error_NoData {
            get {
                return ResourceManager.GetString("QrScan_Error_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a QR scanning is not available on this device..
        /// </summary>
        public static string QrScan_Error_NotAvailable {
            get {
                return ResourceManager.GetString("QrScan_Error_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Camera access denied. Please allow it and retry..
        /// </summary>
        public static string QrScan_Error_PermissionDenied {
            get {
                return ResourceManager.GetString("QrScan_Error_PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Camera failed to start..
        /// </summary>
        public static string QrScan_Error_Stream {
            get {
                return ResourceManager.GetString("QrScan_Error_Stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The QR code targets a different blockchain..
        /// </summary>
        public static string QrScan_Error_WrongNetwork {
            get {
                return ResourceManager.GetString("QrScan_Error_WrongNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The QR references a token different from EURC..
        /// </summary>
        public static string QrScan_Error_WrongToken {
            get {
                return ResourceManager.GetString("QrScan_Error_WrongToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        public static string QrScan_Prompt_Cancel {
            get {
                return ResourceManager.GetString("QrScan_Prompt_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Point the code inside the frame to fill the payment details..
        /// </summary>
        public static string QrScan_Prompt_Message {
            get {
                return ResourceManager.GetString("QrScan_Prompt_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Align the QR code.
        /// </summary>
        public static string QrScan_Prompt_Title {
            get {
                return ResourceManager.GetString("QrScan_Prompt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Receive Payment.
        /// </summary>
        public static string ReceivePaymentTitle {
            get {
                return ResourceManager.GetString("ReceivePaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Recent transactions.
        /// </summary>
        public static string RecentTransactionsTitle {
            get {
                return ResourceManager.GetString("RecentTransactionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Request Details.
        /// </summary>
        public static string RequestDetails {
            get {
                return ResourceManager.GetString("RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Del.
        /// </summary>
        public static string RequestPayment_Backspace {
            get {
                return ResourceManager.GetString("RequestPayment_Backspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OK.
        /// </summary>
        public static string RequestPayment_Confirm {
            get {
                return ResourceManager.GetString("RequestPayment_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Currency:.
        /// </summary>
        public static string RequestPayment_CurrencyLabel {
            get {
                return ResourceManager.GetString("RequestPayment_CurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter a valid amount greater than zero..
        /// </summary>
        public static string RequestPayment_ErrorAmount {
            get {
                return ResourceManager.GetString("RequestPayment_ErrorAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Payment request failed. Please try again..
        /// </summary>
        public static string RequestPayment_ErrorApi {
            get {
                return ResourceManager.GetString("RequestPayment_ErrorApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No internet connection or server unreachable..
        /// </summary>
        public static string RequestPayment_ErrorNetwork {
            get {
                return ResourceManager.GetString("RequestPayment_ErrorNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Payment request sent successfully!.
        /// </summary>
        public static string RequestPayment_Success {
            get {
                return ResourceManager.GetString("RequestPayment_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Request payment.
        /// </summary>
        public static string RequestPayment_Title {
            get {
                return ResourceManager.GetString("RequestPayment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Restore existing wallet.
        /// </summary>
        public static string RestoreWalletButton {
            get {
                return ResourceManager.GetString("RestoreWalletButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid passphrase. Please check all 24 words and try again..
        /// </summary>
        public static string RestoreWalletError {
            get {
                return ResourceManager.GetString("RestoreWalletError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter your 24-word passphrase to restore your wallet..
        /// </summary>
        public static string RestoreWalletInstructions {
            get {
                return ResourceManager.GetString("RestoreWalletInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Restore Wallet.
        /// </summary>
        public static string RestoreWalletTitle {
            get {
                return ResourceManager.GetString("RestoreWalletTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Point the camera at the QR code of the request to automatically fill in the payment details..
        /// </summary>
        public static string ScanQRDescription {
            get {
                return ResourceManager.GetString("ScanQRDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scan QR payment request.
        /// </summary>
        public static string ScanQRTitle {
            get {
                return ResourceManager.GetString("ScanQRTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select language:.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Available balance: {0} {1}.
        /// </summary>
        public static string SendBalanceLabel {
            get {
                return ResourceManager.GetString("SendBalanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Destination address.
        /// </summary>
        public static string SendDestinationLabel {
            get {
                return ResourceManager.GetString("SendDestinationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a At least {0} {1} must remain available for network fees..
        /// </summary>
        public static string SendErrorFeeReserveRequired {
            get {
                return ResourceManager.GetString("SendErrorFeeReserveRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insufficient funds to complete the transaction..
        /// </summary>
        public static string SendErrorInsufficientFunds {
            get {
                return ResourceManager.GetString("SendErrorInsufficientFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Network fees are paid with the native currency of the blockchain. Keep a reserve available to cover costs..
        /// </summary>
        public static string SendFeeNoticeNetwork {
            get {
                return ResourceManager.GetString("SendFeeNoticeNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Native fee balance is low: {0} available, at least {1} recommended..
        /// </summary>
        public static string SendFeeWarningLowFee {
            get {
                return ResourceManager.GetString("SendFeeWarningLowFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Max.
        /// </summary>
        public static string SendMaxButton {
            get {
                return ResourceManager.GetString("SendMaxButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Send {0}.
        /// </summary>
        public static string SendPageTitle {
            get {
                return ResourceManager.GetString("SendPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Send Payment.
        /// </summary>
        public static string SendPaymentButton {
            get {
                return ResourceManager.GetString("SendPaymentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scan QR.
        /// </summary>
        public static string SendScanButton {
            get {
                return ResourceManager.GetString("SendScanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hide {0}.
        /// </summary>
        public static string SetupAssetHideLabel {
            get {
                return ResourceManager.GetString("SetupAssetHideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No assets configured..
        /// </summary>
        public static string SetupAssetNoneConfigured {
            get {
                return ResourceManager.GetString("SetupAssetNoneConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Choose which assets to show in the main menu..
        /// </summary>
        public static string SetupAssetPreferencesDescription {
            get {
                return ResourceManager.GetString("SetupAssetPreferencesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Asset preferences.
        /// </summary>
        public static string SetupAssetPreferencesTitle {
            get {
                return ResourceManager.GetString("SetupAssetPreferencesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Checking requirements….
        /// </summary>
        public static string SetupBiometricChecking {
            get {
                return ResourceManager.GetString("SetupBiometricChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Require fingerprint when the app starts on this device..
        /// </summary>
        public static string SetupBiometricDescription {
            get {
                return ResourceManager.GetString("SetupBiometricDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Biometric protection.
        /// </summary>
        public static string SetupBiometricTitle {
            get {
                return ResourceManager.GetString("SetupBiometricTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Require fingerprint.
        /// </summary>
        public static string SetupBiometricToggleLabel {
            get {
                return ResourceManager.GetString("SetupBiometricToggleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Updating currency….
        /// </summary>
        public static string SetupFiatUpdating {
            get {
                return ResourceManager.GetString("SetupFiatUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Settings.
        /// </summary>
        public static string SetupTitle {
            get {
                return ResourceManager.GetString("SetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Share Request.
        /// </summary>
        public static string ShareRequest {
            get {
                return ResourceManager.GetString("ShareRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sending Solana transaction failed: {0}.
        /// </summary>
        public static string SolanaTransactionSendFailed {
            get {
                return ResourceManager.GetString("SolanaTransactionSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Start QR scan.
        /// </summary>
        public static string StartQRScan {
            get {
                return ResourceManager.GetString("StartQRScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Secure storage is unavailable in this hosting environment. Ensure the app is running locally and try again..
        /// </summary>
        public static string StorageUnavailableError {
            get {
                return ResourceManager.GetString("StorageUnavailableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insufficient funds for swap..
        /// </summary>
        public static string SwapError_InsufficientFunds {
            get {
                return ResourceManager.GetString("SwapError_InsufficientFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User address is required..
        /// </summary>
        public static string SwapError_InvalidAddress {
            get {
                return ResourceManager.GetString("SwapError_InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Amount must be positive..
        /// </summary>
        public static string SwapError_InvalidAmount {
            get {
                return ResourceManager.GetString("SwapError_InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid asset(s) specified..
        /// </summary>
        public static string SwapError_InvalidAsset {
            get {
                return ResourceManager.GetString("SwapError_InvalidAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Network error during swap..
        /// </summary>
        public static string SwapError_NetworkError {
            get {
                return ResourceManager.GetString("SwapError_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This swap type is not supported..
        /// </summary>
        public static string SwapError_NotSupported {
            get {
                return ResourceManager.GetString("SwapError_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An unknown error occurred during swap..
        /// </summary>
        public static string SwapError_Unknown {
            get {
                return ResourceManager.GetString("SwapError_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The conversion between these two cryptocurrencies is not supported..
        /// </summary>
        public static string SwapNotSupported {
            get {
                return ResourceManager.GetString("SwapNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dark.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Light.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Choose your preferred interface theme:.
        /// </summary>
        public static string ThemePreferenceDescription {
            get {
                return ResourceManager.GetString("ThemePreferenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a App theme.
        /// </summary>
        public static string ThemePreferenceTitle {
            get {
                return ResourceManager.GetString("ThemePreferenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a System default.
        /// </summary>
        public static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a To asset.
        /// </summary>
        public static string ToAsset {
            get {
                return ResourceManager.GetString("ToAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Transaction sent: {0}.
        /// </summary>
        public static string TransactionSentFormat {
            get {
                return ResourceManager.GetString("TransactionSentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Utilities.
        /// </summary>
        public static string UtilitiesTitle {
            get {
                return ResourceManager.GetString("UtilitiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Value in.
        /// </summary>
        public static string ValueIn {
            get {
                return ResourceManager.GetString("ValueIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Available balance:.
        /// </summary>
        public static string WalletBalancePlaceholder {
            get {
                return ResourceManager.GetString("WalletBalancePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Wallet created successfully. The account key has been stored locally..
        /// </summary>
        public static string WalletCreatedSuccess {
            get {
                return ResourceManager.GetString("WalletCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a EURC balance:.
        /// </summary>
        public static string WalletEurcBalanceLabel {
            get {
                return ResourceManager.GetString("WalletEurcBalanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Transactions in {0} consume part of the balance as network fees. Keep at least {1} in reserve..
        /// </summary>
        public static string WalletFeeInfoNative {
            get {
                return ResourceManager.GetString("WalletFeeInfoNative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Transactions in {0} consume part of the balance as network fees..
        /// </summary>
        public static string WalletFeeInfoNativeGeneral {
            get {
                return ResourceManager.GetString("WalletFeeInfoNativeGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a It&apos;s recommended to keep at least {0} {1} in reserve..
        /// </summary>
        public static string WalletFeeInfoRecommended {
            get {
                return ResourceManager.GetString("WalletFeeInfoRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Transactions in {0} require fees paid in {1}..
        /// </summary>
        public static string WalletFeeInfoRequirement {
            get {
                return ResourceManager.GetString("WalletFeeInfoRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open {0} wallet.
        /// </summary>
        public static string WalletFeeOpenFeeWallet {
            get {
                return ResourceManager.GetString("WalletFeeOpenFeeWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Available {0} balance: {1}..
        /// </summary>
        public static string WalletFeeWarningBalance {
            get {
                return ResourceManager.GetString("WalletFeeWarningBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a To send {0} you must hold {1} to cover network fees..
        /// </summary>
        public static string WalletFeeWarningRequirement {
            get {
                return ResourceManager.GetString("WalletFeeWarningRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Keep at least {1} {0} available to cover network costs..
        /// </summary>
        public static string WalletFeeWarningReserveRecommendation {
            get {
                return ResourceManager.GetString("WalletFeeWarningReserveRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Warning:.
        /// </summary>
        public static string WalletFeeWarningTitle {
            get {
                return ResourceManager.GetString("WalletFeeWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} wallet.
        /// </summary>
        public static string WalletLabelFormat {
            get {
                return ResourceManager.GetString("WalletLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Welcome to ClickPay Wallet.
        /// </summary>
        public static string WalletOnboardingTitle {
            get {
                return ResourceManager.GetString("WalletOnboardingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Wallet restored successfully. The account key has been updated locally..
        /// </summary>
        public static string WalletRestoredSuccess {
            get {
                return ResourceManager.GetString("WalletRestoredSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Solana address (EURC):.
        /// </summary>
        public static string WalletSolanaAddressLabel {
            get {
                return ResourceManager.GetString("WalletSolanaAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Timeout while retrieving the balance required for network fees..
        /// </summary>
        public static string WalletTimeoutFeeBalance {
            get {
                return ResourceManager.GetString("WalletTimeoutFeeBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Timeout while refreshing the fiat value. Please try again later..
        /// </summary>
        public static string WalletTimeoutFiat {
            get {
                return ResourceManager.GetString("WalletTimeoutFiat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Timeout while loading wallet data. Check your connection and retry..
        /// </summary>
        public static string WalletTimeoutOverview {
            get {
                return ResourceManager.GetString("WalletTimeoutOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Timeout while checking the local wallet. Please try again..
        /// </summary>
        public static string WalletTimeoutVault {
            get {
                return ResourceManager.GetString("WalletTimeoutVault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Choose to create a new wallet or restore an existing one using your passphrase..
        /// </summary>
        public static string WalletWelcomeDescription {
            get {
                return ResourceManager.GetString("WalletWelcomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Wallet Management.
        /// </summary>
        public static string WalletWelcomeTitle {
            get {
                return ResourceManager.GetString("WalletWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Extended public key (account):.
        /// </summary>
        public static string WalletXpubLabel {
            get {
                return ResourceManager.GetString("WalletXpubLabel", resourceCulture);
            }
        }
    }
}
